### ISSUE TITLE
Dynamically added keywords not discovered by VSCode's Python IntelliSense

### ISSUE THREAD

**Issue by cmin764** [robotframework/PythonLibCore#95] opened 2022-09-15 12:31 UTC
As the title describes, when adopting this `DynamicCore` pattern with dynamically registering methods at class instantiation time based on the registered `ContextAware` derivates, everything works just fine within Robot Framework space (mainly due to the generated & packaged libspecs), but with VSCode while editing Python code:

<img width="1028" alt="Screenshot 2022-09-15 at 15 07 24" src="https://user-images.githubusercontent.com/709053/190401349-46d7e97a-ea61-4e8f-b88b-51f01ea8cf3f.png">

Robot [example](https://github.com/cmin764/robots/blob/main/intelli/task.py#L15-L16):
- `selenium_lib.open_browser` from the pure RF Selenium library is detected due to the related _*.pyi_ module interface, where the downside is the absence of the docstring.
<img width="837" alt="Screenshot 2022-09-15 at 15 07 10" src="https://user-images.githubusercontent.com/709053/190404011-cdc1e46a-5518-4a80-8e16-b1cd18c6ed6d.png">

- Without such interface, like in the `pdf_lib.open_pdf` case, it is even worse, as the keyword method isn't even detected.

1. Is this a known limitation? And no matter the answer, is there any plan on supporting VSCode detecting such dynamically added methods when working in **Python**?
2. Why this black-magic pattern when we could have just inherited from all the bases (library components) in the final library class? (so method resolution is done at class creation time rather than instantiation time)

----

Remember, this has nothing to do with `rpaframework` or even Robocorp. It is purely about crafting a library by:
1. Inheriting from `DynamicCore` on the final library class and registering under its `__init__` the library components. (the pattern used in RF)
3. Editing robot code with VSCode in Python while having Microsoft's official Python extension enabled.
4. Not being able to auto-complete code nor seeing any of the methods or their definitions/docstrings.
  a. Exception when generating with _mypy_ a stub file describing the full interface of the final library instance. (like observed with Selenium)

Related to: https://github.com/robocorp/rpaframework/issues/621

**Comment by aaltat** [comment] 2022-09-15 14:00
1)
We only support Robot Framework dynamic library API. If IDE and/or plugins do keyword discovery in some other way, then it's problem for those IDE. Example VSCode Robot Framework language server implementation should fully support dynamic library API. 

2) 
Well, it's not black magic,  PythonLibCore (PLC) is just one way to implement Robot Framework dynamic library API. If one has small library, with few keywords, then PLC doesn't bring benefits and implementing keywords in a single object is, usually, better way. But PLC brings lots of benefits with large libraries, like SeleniumLibrary or Browser library,  where multi inheritance comes really a big problem and it's usually easier to implement things in a isolated classes.

**Comment by aaltat** [comment] 2022-09-15 15:10
I wrote an comment in the  rpaframework side and explained that the problem is actually in their side. Hopefully they will fix the problem in their side, because the problem is in rpaframework, it does not support dynamic library API. 

Because there is not anything to fix in PLC side, I am going to close this issue.

**Closed** 2022-09-15 15:16 UTC

**Comment by pekkaklarck** [comment] 2022-09-16 08:20
Agreed with @aaltat. Notice that if you want to just inherit from all library components, you don't need any tooling dor that:
```python
class MyLib(Comp1, Comp2, Comp3):
    ...
```
This is how SL worked earlier and how BuiltIn still works.
